name: build

# we have multiple workflows - this helps to distinguish for them
run-name: "${{ github.event.pull_request.title || github.head_ref }} - Codestyle"

on:
  push:
    branches: [ develop, release/* ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven - Verify, Jacoco and Package
        run: mvn --batch-mode -U verify test jacoco:report-aggregate package

      - name: Sonar - Analyze
        # Dependabot has no access to the SONAR_TOKEN secret, so we need to skip sonar.
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify test jacoco:report-aggregate package sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=ehrbase \
            -Dsonar.projectKey=ehrbase_openEHR_SDK \
            -Dsonar.exclusions=test/** \
            -Dsonar.coverage.exclusions=test/**,test-data/**/*,opt-14/**/*,response-dto/**/* \
            -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/test-coverage/target/site/jacoco-overall-coverage/jacoco.xml

